# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _cODP
else:
    import _cODP

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def ODP_parseString(src):
    return _cODP.ODP_parseString(src)

def ODP_parseFile(path):
    return _cODP.ODP_parseFile(path)
class ODPNode(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    doc = property(_cODP.ODPNode_doc_get, _cODP.ODPNode_doc_set)
    pos = property(_cODP.ODPNode_pos_get, _cODP.ODPNode_pos_set)

    def __init__(self, node):
        _cODP.ODPNode_swiginit(self, _cODP.new_ODPNode(node))
    ELEMENT_NODE = _cODP.ODPNode_ELEMENT_NODE
    ATTRIBUTE_NODE = _cODP.ODPNode_ATTRIBUTE_NODE
    TEXT_NODE = _cODP.ODPNode_TEXT_NODE
    CDATA_SECTION_NODE = _cODP.ODPNode_CDATA_SECTION_NODE
    ENTITY_REFERENCE_NODE = _cODP.ODPNode_ENTITY_REFERENCE_NODE
    ENTITY_NODE = _cODP.ODPNode_ENTITY_NODE
    PROCESSING_INSTRUCTION_NODE = _cODP.ODPNode_PROCESSING_INSTRUCTION_NODE
    COMMENT_NODE = _cODP.ODPNode_COMMENT_NODE
    DOCUMENT_NODE = _cODP.ODPNode_DOCUMENT_NODE
    DOCUMENT_TYPE_NODE = _cODP.ODPNode_DOCUMENT_TYPE_NODE
    DOCUMENT_FRAGMENT_NODE = _cODP.ODPNode_DOCUMENT_FRAGMENT_NODE
    NOTATION_NODE = _cODP.ODPNode_NOTATION_NODE

    def getNodeName(self):
        return _cODP.ODPNode_getNodeName(self)

    def getNodeValue(self):
        return _cODP.ODPNode_getNodeValue(self)

    def setNodeValue(self, v):
        return _cODP.ODPNode_setNodeValue(self, v)

    def getNodeType(self):
        return _cODP.ODPNode_getNodeType(self)

    def getParentNode(self):
        return _cODP.ODPNode_getParentNode(self)

    def getChildNodes(self):
        return _cODP.ODPNode_getChildNodes(self)

    def getFirstChild(self):
        return _cODP.ODPNode_getFirstChild(self)

    def getLastChild(self):
        return _cODP.ODPNode_getLastChild(self)

    def getPreviousSibling(self):
        return _cODP.ODPNode_getPreviousSibling(self)

    def getNextSibling(self):
        return _cODP.ODPNode_getNextSibling(self)

    def getAttributes(self):
        return _cODP.ODPNode_getAttributes(self)

    def getOwnerDocument(self):
        return _cODP.ODPNode_getOwnerDocument(self)

    def hasChildNodes(self):
        return _cODP.ODPNode_hasChildNodes(self)

    def up(self):
        return _cODP.ODPNode_up(self)

    def down(self):
        return _cODP.ODPNode_down(self)

    def next(self):
        return _cODP.ODPNode_next(self)

    def previous(self):
        return _cODP.ODPNode_previous(self)

    def poschar(self):
        return _cODP.ODPNode_poschar(self)
    __swig_destroy__ = _cODP.delete_ODPNode

# Register ODPNode in _cODP:
_cODP.ODPNode_swigregister(ODPNode)
class ODPDOMImplementation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def hasFeature(self, feature, version):
        return _cODP.ODPDOMImplementation_hasFeature(self, feature, version)

    def __init__(self):
        _cODP.ODPDOMImplementation_swiginit(self, _cODP.new_ODPDOMImplementation())
    __swig_destroy__ = _cODP.delete_ODPDOMImplementation

# Register ODPDOMImplementation in _cODP:
_cODP.ODPDOMImplementation_swigregister(ODPDOMImplementation)
class ODPDocument(ODPNode):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def getDoctype(self):
        return _cODP.ODPDocument_getDoctype(self)

    def getImplementation(self):
        return _cODP.ODPDocument_getImplementation(self)

    def getDocumentElement(self):
        return _cODP.ODPDocument_getDocumentElement(self)

    def createElement(self, tagName):
        return _cODP.ODPDocument_createElement(self, tagName)

    def createDocumentFragment(self):
        return _cODP.ODPDocument_createDocumentFragment(self)

    def createTextNode(self, data):
        return _cODP.ODPDocument_createTextNode(self, data)

    def createComment(self, data):
        return _cODP.ODPDocument_createComment(self, data)

    def createCDATASection(self, data):
        return _cODP.ODPDocument_createCDATASection(self, data)

    def createProcessingInstruction(self, target, data):
        return _cODP.ODPDocument_createProcessingInstruction(self, target, data)

    def createAttribute(self, name):
        return _cODP.ODPDocument_createAttribute(self, name)

    def createEntityReference(self, name):
        return _cODP.ODPDocument_createEntityReference(self, name)

    def getElementsByTagName(self, tagname):
        return _cODP.ODPDocument_getElementsByTagName(self, tagname)
    __swig_destroy__ = _cODP.delete_ODPDocument

# Register ODPDocument in _cODP:
_cODP.ODPDocument_swigregister(ODPDocument)
class ODPDocumentParent(ODPDocument):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _cODP.delete_ODPDocumentParent

# Register ODPDocumentParent in _cODP:
_cODP.ODPDocumentParent_swigregister(ODPDocumentParent)
class ODPElement(ODPNode):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node):
        _cODP.ODPElement_swiginit(self, _cODP.new_ODPElement(node))

    def getTagName(self):
        return _cODP.ODPElement_getTagName(self)

    def getAttribute(self, name):
        return _cODP.ODPElement_getAttribute(self, name)

    def setAttribute(self, name, value):
        return _cODP.ODPElement_setAttribute(self, name, value)

    def removeAttribute(self, name):
        return _cODP.ODPElement_removeAttribute(self, name)

    def getAttributeNode(self, name):
        return _cODP.ODPElement_getAttributeNode(self, name)

    def setAttributeNode(self, newAttr):
        return _cODP.ODPElement_setAttributeNode(self, newAttr)

    def removeAttributeNode(self, oldAttr):
        return _cODP.ODPElement_removeAttributeNode(self, oldAttr)

    def getElementsByTagName(self, name):
        return _cODP.ODPElement_getElementsByTagName(self, name)

    def normalize(self):
        return _cODP.ODPElement_normalize(self)

    def refreshAttr(self):
        return _cODP.ODPElement_refreshAttr(self)
    __swig_destroy__ = _cODP.delete_ODPElement

# Register ODPElement in _cODP:
_cODP.ODPElement_swigregister(ODPElement)
class ODPCharacterData(ODPNode):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def getData(self):
        return _cODP.ODPCharacterData_getData(self)

    def setData(self, s):
        return _cODP.ODPCharacterData_setData(self, s)

    def __init__(self, node):
        _cODP.ODPCharacterData_swiginit(self, _cODP.new_ODPCharacterData(node))

    def getLength(self):
        return _cODP.ODPCharacterData_getLength(self)

    def substringData(self, offset, count):
        return _cODP.ODPCharacterData_substringData(self, offset, count)

    def appendData(self, arg):
        return _cODP.ODPCharacterData_appendData(self, arg)

    def insertData(self, offset, arg):
        return _cODP.ODPCharacterData_insertData(self, offset, arg)

    def deleteData(self, offset, count):
        return _cODP.ODPCharacterData_deleteData(self, offset, count)

    def replaceData(self, offset, count, arg):
        return _cODP.ODPCharacterData_replaceData(self, offset, count, arg)
    __swig_destroy__ = _cODP.delete_ODPCharacterData

# Register ODPCharacterData in _cODP:
_cODP.ODPCharacterData_swigregister(ODPCharacterData)
class ODPText(ODPCharacterData):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node):
        _cODP.ODPText_swiginit(self, _cODP.new_ODPText(node))

    def splitText(self, offset):
        return _cODP.ODPText_splitText(self, offset)
    __swig_destroy__ = _cODP.delete_ODPText

# Register ODPText in _cODP:
_cODP.ODPText_swigregister(ODPText)
class ODPComment(ODPCharacterData):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node):
        _cODP.ODPComment_swiginit(self, _cODP.new_ODPComment(node))
    __swig_destroy__ = _cODP.delete_ODPComment

# Register ODPComment in _cODP:
_cODP.ODPComment_swigregister(ODPComment)
class ODPCDATASection(ODPText):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node):
        _cODP.ODPCDATASection_swiginit(self, _cODP.new_ODPCDATASection(node))
    __swig_destroy__ = _cODP.delete_ODPCDATASection

# Register ODPCDATASection in _cODP:
_cODP.ODPCDATASection_swigregister(ODPCDATASection)
class ODPNodeList(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def item(self, index):
        return _cODP.ODPNodeList_item(self, index)

    def getLength(self):
        return _cODP.ODPNodeList_getLength(self)

    def __init__(self):
        _cODP.ODPNodeList_swiginit(self, _cODP.new_ODPNodeList())
    __swig_destroy__ = _cODP.delete_ODPNodeList

# Register ODPNodeList in _cODP:
_cODP.ODPNodeList_swigregister(ODPNodeList)
class ODPChildList(ODPNodeList):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node):
        _cODP.ODPChildList_swiginit(self, _cODP.new_ODPChildList(node))

    def item(self, index):
        return _cODP.ODPChildList_item(self, index)

    def getLength(self):
        return _cODP.ODPChildList_getLength(self)
    __swig_destroy__ = _cODP.delete_ODPChildList

# Register ODPChildList in _cODP:
_cODP.ODPChildList_swigregister(ODPChildList)
class ODPElementsByTagNameList(ODPNodeList):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node, tag):
        _cODP.ODPElementsByTagNameList_swiginit(self, _cODP.new_ODPElementsByTagNameList(node, tag))
    __swig_destroy__ = _cODP.delete_ODPElementsByTagNameList

    def item(self, index):
        return _cODP.ODPElementsByTagNameList_item(self, index)

    def getLength(self):
        return _cODP.ODPElementsByTagNameList_getLength(self)

# Register ODPElementsByTagNameList in _cODP:
_cODP.ODPElementsByTagNameList_swigregister(ODPElementsByTagNameList)
class ODPChildrenByTagNameList(ODPNodeList):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node, tag):
        _cODP.ODPChildrenByTagNameList_swiginit(self, _cODP.new_ODPChildrenByTagNameList(node, tag))
    __swig_destroy__ = _cODP.delete_ODPChildrenByTagNameList

    def item(self, index):
        return _cODP.ODPChildrenByTagNameList_item(self, index)

    def getLength(self):
        return _cODP.ODPChildrenByTagNameList_getLength(self)

# Register ODPChildrenByTagNameList in _cODP:
_cODP.ODPChildrenByTagNameList_swigregister(ODPChildrenByTagNameList)
class ODPNamedNodeMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def getNamedItem(self, name):
        return _cODP.ODPNamedNodeMap_getNamedItem(self, name)

    def setNamedItem(self, arg):
        return _cODP.ODPNamedNodeMap_setNamedItem(self, arg)

    def removeNamedItem(self, name):
        return _cODP.ODPNamedNodeMap_removeNamedItem(self, name)

    def item(self, index):
        return _cODP.ODPNamedNodeMap_item(self, index)

    def getLength(self):
        return _cODP.ODPNamedNodeMap_getLength(self)

    def __init__(self):
        _cODP.ODPNamedNodeMap_swiginit(self, _cODP.new_ODPNamedNodeMap())
    __swig_destroy__ = _cODP.delete_ODPNamedNodeMap

# Register ODPNamedNodeMap in _cODP:
_cODP.ODPNamedNodeMap_swigregister(ODPNamedNodeMap)
class ODPAttributeMap(ODPNamedNodeMap):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node):
        _cODP.ODPAttributeMap_swiginit(self, _cODP.new_ODPAttributeMap(node))

    def setNode(self, node):
        return _cODP.ODPAttributeMap_setNode(self, node)

    def getAttribute(self, name):
        return _cODP.ODPAttributeMap_getAttribute(self, name)

    def getNamedItem(self, name):
        return _cODP.ODPAttributeMap_getNamedItem(self, name)

    def item(self, index):
        return _cODP.ODPAttributeMap_item(self, index)

    def getLength(self):
        return _cODP.ODPAttributeMap_getLength(self)
    __swig_destroy__ = _cODP.delete_ODPAttributeMap

# Register ODPAttributeMap in _cODP:
_cODP.ODPAttributeMap_swigregister(ODPAttributeMap)
class ODPAttr(ODPNode):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, node):
        _cODP.ODPAttr_swiginit(self, _cODP.new_ODPAttr(node))

    def getName(self):
        return _cODP.ODPAttr_getName(self)

    def getSpecified(self):
        return _cODP.ODPAttr_getSpecified(self)

    def getValue(self):
        return _cODP.ODPAttr_getValue(self)

    def setValue(self, s):
        return _cODP.ODPAttr_setValue(self, s)
    __swig_destroy__ = _cODP.delete_ODPAttr

# Register ODPAttr in _cODP:
_cODP.ODPAttr_swigregister(ODPAttr)

