"""Compose INCAR presets from the user's Q-robot generator, without GUI dependencies."""

import json
import os
import re

import p4vasp


def load_presets():
    path = os.path.join(p4vasp.p4vasp_home, "data", "incar", "presets.json")
    with open(path, encoding="utf-8") as stream:
        return json.load(stream)


def parse_custom(text):
    """Read assignments, including VASP comments and semicolon-separated tags."""
    params = {}
    for number, line in enumerate(text.splitlines(), 1):
        line = re.split(r"[#!]", line, maxsplit=1)[0]
        for assignment in line.split(";"):
            if not assignment.strip():
                continue
            key, separator, value = assignment.partition("=")
            key, value = key.strip().upper(), value.strip()
            if not separator or not re.fullmatch(r"[A-Z][A-Z0-9_]*", key) or (not value and key != "MAGMOM"):
                raise ValueError("Custom parameters, line %d: expected TAG = value." % number)
            params[key] = value
    return params


def species_from_structure(structure):
    """Keep POSCAR species blocks in order, including repeated element blocks."""
    if structure is None or not len(structure):
        return []
    species = []
    for index, count in enumerate(structure.info.atomspertype):
        if count:
            symbol = str(structure.info.getRecord(index).element).strip()
            species.append((symbol, int(count)))
    if sum(count for _, count in species) != len(structure):
        raise ValueError("Geometry species counts do not match its atom count.")
    return species


def geometry_parameters(species, selected, element_data, custom):
    result = {}
    needed = []
    if "MAGMOM" in selected and "MAGMOM" not in custom:
        result["MAGMOM"] = "  ".join("%d*0" % count for _, count in species)
    if "DFT+U" in selected:
        needed.extend(("LDAUL", "LDAUU", "LDAUJ"))
    missing = [key for key in needed if key not in custom]
    if not missing:
        return result
    if not species or any(symbol not in element_data["mag_value"] for symbol, _ in species):
        raise ValueError("Load a geometry with element names, or supply %s in Custom parameters."
                         % ", ".join(missing))
    u, j = element_data["u_value"], element_data["j_value"]
    values = {
        "LDAUL": [2 if symbol in u else -1 for symbol, _ in species],
        "LDAUU": [u.get(symbol, 0) for symbol, _ in species],
        "LDAUJ": [j.get(symbol, 0) for symbol, _ in species],
    }
    for key in missing:
        if key in values:
            result[key] = "  ".join(map(str, values[key]))
    return result


def generate_incar(config, selected, sections, custom_text="", species=(), system_name=""):
    """Merge standard < other presets < tasks < geometry helpers < custom tags."""
    custom = parse_custom(custom_text)
    groups = []
    for section in sections:
        if section != "d_system":
            groups.append(("Standard: " + section.removeprefix("d_").title(),
                           config["standard"][section]))
    categories = config["categories"]
    for category in [key for key in categories if key != "Tasks"] + ["Tasks"]:
        for name in selected:
            if name in categories.get(category, {}):
                groups.append((category + ": " + name, categories[category][name]["params"]))
    groups.append(("Geometry (Q-robot element defaults)",
                   geometry_parameters(species, selected, config["elements"], custom)))
    groups.append(("Custom parameters", custom))
    merged, owners = {}, {}
    for index, (_, params) in enumerate(groups):
        for key, value in params.items():
            key = key.strip().upper()
            merged[key], owners[key] = str(value), index
    title = custom.get("SYSTEM", system_name or "Generated by p4vasp / Q-robot")
    title = re.sub(r"[\r\n;#!]", " ", title)
    lines = ["SYSTEM = " + title, ""]
    for index, (name, _) in enumerate(groups):
        keys = sorted(key for key in merged if owners[key] == index and key != "SYSTEM")
        if keys:
            lines.append("# " + name)
            for key in keys:
                if key == "MAGMOM" and species:
                    lines.append("# " + ", ".join("%s (%d)" % (symbol or "?", count)
                                                  for symbol, count in species))
                lines.append("%s = %s" % (key, merged[key]))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"
